pub fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .to_path_buf()
}

pub fn fixture_dashboard() -> yaoshi_screen::DashboardSnapshot {
    use yaoshi_screen::{
        DashboardCoreRow, DashboardDiskRow, DashboardNetworkRow, DashboardSnapshot,
        NegotiatedDisplay, Surface,
    };

    DashboardSnapshot {
        display: NegotiatedDisplay::fixture(Surface::Dashboard, 184, 52),
        hostname: "yaoshi".to_string(),
        uptime: "1m 2.000s".to_string(),
        kernel_release: "6.12.0-yaoshi".to_string(),
        system_vendor: "Yaoshi".to_string(),
        product_name: "Test Machine".to_string(),
        board_vendor: "Yaoshi".to_string(),
        board_name: "Test Board".to_string(),
        firmware_vendor: "Yaoshi".to_string(),
        firmware_version: "1.0.0".to_string(),
        prepare_state: "applied".to_string(),
        root_expansion_state: "expanded".to_string(),
        root_partuuid: "5c5c9f71-bc23-4f8d-80b2-6d4bb64a0f33".to_string(),
        root_label: "YAOSHI_ROOT".to_string(),
        ssh_ready_state: "ready".to_string(),
        ssh_root_key_state: "enabled".to_string(),
        authorized_key_count: "1".to_string(),
        ssh_listening_state: "listening".to_string(),
        ssh_process_state: "running".to_string(),
        networkd_process_state: "running".to_string(),
        dashboard_process_state: "running".to_string(),
        root_shell_state: "running".to_string(),
        rescue_shell_state: "running".to_string(),
        network_state: "ready".to_string(),
        kernel_alert_state: "none".to_string(),
        kernel_warning_count: "0".to_string(),
        kernel_error_count: "0".to_string(),
        ssh_access_address: "192.0.2.10".to_string(),
        ssh_access_summary: "eth0".to_string(),
        route_iface: "eth0".to_string(),
        route_address: "192.0.2.10".to_string(),
        default_gateway: "192.0.2.1".to_string(),
        route_metric: "100".to_string(),
        cpu_used: "12.000%".to_string(),
        cpu_model: "Yaoshi CPU".to_string(),
        logical_cpu_count: "1".to_string(),
        cpu_state: String::new(),
        load1: "0.100".to_string(),
        load5: "0.080".to_string(),
        load15: "0.040".to_string(),
        memory_used_percent: "20.000%".to_string(),
        memory_state: String::new(),
        memory_used: "512.000 MiB".to_string(),
        memory_total: "2.000 GiB".to_string(),
        memory_dimm_summary: "2 DIMMs - 2.000 GiB - Yaoshi Memory x2 - 3200 MT/s - ecc yes"
            .to_string(),
        root_used_percent: "30.000%".to_string(),
        root_state: String::new(),
        root_used: "1.000 GiB".to_string(),
        root_total: "4.000 GiB".to_string(),
        root_inode_percent: "4.000%".to_string(),
        inode_state: String::new(),
        root_inode_usage: "1000/25000".to_string(),
        thermal: "unavailable".to_string(),
        thermal_state: "unavailable".to_string(),
        thermal_source: "unavailable".to_string(),
        cpu_pressure: "0.000%".to_string(),
        memory_pressure: "0.000%".to_string(),
        io_pressure: "0.000%".to_string(),
        top_cpu_process: "unavailable".to_string(),
        process_count: "1".to_string(),
        running_process_count: "1".to_string(),
        blocked_process_count: "0".to_string(),
        memory_available: "1.500 GiB".to_string(),
        memory_cache: "128.000 MiB".to_string(),
        memory_dirty: "0 B".to_string(),
        swap_used: "0 B".to_string(),
        swap_total: "0 B".to_string(),
        swap_used_percent: "0.000%".to_string(),
        top_rss_process: "unavailable".to_string(),
        memory_full_pressure: "0.000%".to_string(),
        io_full_pressure: "0.000%".to_string(),
        disk_count: "1".to_string(),
        filesystem_rows: Vec::new(),
        network_interface_count: "1".to_string(),
        route_rows: Vec::new(),
        grow_root_service: "expanded".to_string(),
        ssh_service: "running".to_string(),
        networkd_service: "running".to_string(),
        dashboard_service: "running".to_string(),
        root_shell_service: "running".to_string(),
        disk_read_rate: "measuring".to_string(),
        disk_write_rate: "measuring".to_string(),
        disk_read_iops: "measuring".to_string(),
        disk_write_iops: "measuring".to_string(),
        network_rx_rate: "measuring".to_string(),
        network_tx_rate: "measuring".to_string(),
        network_rx_packet_rate: "measuring".to_string(),
        network_tx_packet_rate: "measuring".to_string(),
        network_rx_error_rate: "measuring".to_string(),
        network_tx_error_rate: "measuring".to_string(),
        network_rx_drop_rate: "measuring".to_string(),
        network_tx_drop_rate: "measuring".to_string(),
        network_error_state: String::new(),
        interface_attention_count: "0".to_string(),
        core_rows: vec![DashboardCoreRow {
            index: 0,
            used_percent: "12.000%".to_string(),
        }],
        disk_rows: vec![DashboardDiskRow {
            is_root: true,
            dev: "/dev/vda".to_string(),
            size: "5.000 GiB".to_string(),
            transport: "virtio".to_string(),
            vendor: "Yaoshi".to_string(),
            model: "Test Disk".to_string(),
            display: "Yaoshi Test Disk".to_string(),
            serial: "SERIAL-vda".to_string(),
            partitioned: "4.000 GiB".to_string(),
            fs: "/ 1.000 GiB/4.000 GiB 30.000%".to_string(),
        }],
        network_rows: vec![DashboardNetworkRow {
            is_route: true,
            is_access: true,
            iface: "eth0".to_string(),
            role: "access".to_string(),
            kind: "physical".to_string(),
            state: "up".to_string(),
            addresses: "192.0.2.10".to_string(),
            mac: "unavailable".to_string(),
            mtu: "1500".to_string(),
            speed: "1000 Mb/s".to_string(),
            rx_rate: "measuring".to_string(),
            tx_rate: "measuring".to_string(),
            rx_drop_rate: "measuring".to_string(),
            tx_drop_rate: "measuring".to_string(),
            alert_state: String::new(),
        }],
        disk_link_summary: "nvme 0 - sata/scsi 0 - virtio 1 - usb 0 - mmc 0 - other 0".to_string(),
    }
}
